# Generated by Django 6.0.4 on 2026-05-30 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeReglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CASH', 'Cash à la livraison'), ('CRYPTO', 'Crypto-monnaie')], max_length=50, unique=True, verbose_name='Nom')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé affiché')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name="Nom de l'icône")),
            ],
            options={
                'verbose_name': 'Mode de règlement',
                'verbose_name_plural': 'Modes de règlement',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Numéro de commande')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('EN_PREPARATION', 'En préparation'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('REMBOURSEE', 'Remboursée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('adresse_livraison_texte', models.TextField(blank=True, null=True, verbose_name='Adresse de livraison (snapshot)')),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sous-total')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais de livraison')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('note_client', models.TextField(blank=True, null=True, verbose_name='Note du client')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('mode_reglement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='store.modereglement', verbose_name='Mode de règlement')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255, verbose_name='Nom du produit (snapshot)')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire (snapshot)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commande_items', to='vendor.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporteur')),
                ('numero_suivi', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Numéro de suivi')),
                ('url_suivi', models.URLField(blank=True, null=True, verbose_name='URL de suivi')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'expédition"), ('EN_TRANSIT', 'En transit'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('ECHOUEE', 'Échec de livraison'), ('RETOURNEE', 'Retournée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_estimee', models.DateField(blank=True, null=True, verbose_name='Date de livraison estimée')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note transporteur')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='store.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Clé de session (guest)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-mis_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix unitaire (au moment de l'ajout)")),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.panier', verbose_name='Panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='vendor.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('panier', 'produit')},
            },
        ),
    ]
