# Generated by Django 6.0.4 on 2026-05-30 20:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adresse', models.CharField(choices=[('DOMICILE', 'Domicile'), ('BUREAU', 'Bureau'), ('AUTRE', 'Autre')], default='DOMICILE', max_length=10, verbose_name="Type d'adresse")),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse_ligne1', models.CharField(max_length=255, verbose_name='Adresse ligne 1')),
                ('adresse_ligne2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse ligne 2')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région / État')),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-par_defaut', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYPAL', 'PayPal'), ('VIREMENT', 'Virement bancaire')], max_length=20, verbose_name='Type')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé (ex: Visa se terminant par 4242)')),
                ('token_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token / Référence prestataire')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('expire_le', models.DateField(blank=True, null=True, verbose_name='Expire le')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['-par_defaut', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Référence de transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INITIE', 'Initié'), ('VALIDE', 'Validé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('reponse_prestataire', models.JSONField(blank=True, null=True, verbose_name='Réponse prestataire (JSON)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='store.commande', verbose_name='Commande')),
                ('moyen_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='customer.moyenpaiement', verbose_name='Moyen de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1 à 5)')),
                ('titre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='vendor.produit', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-cree_le'],
                'unique_together': {('produit', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favoris', to='vendor.produit', verbose_name='Produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-ajoute_le'],
                'unique_together': {('user', 'produit')},
            },
        ),
    ]
