# Generated by Django 6.0.4 on 2026-05-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0014_alter_city_search_names"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adresse",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adresses",
                to="cities_light.city",
                verbose_name="Ville (Cities Light)",
            ),
        ),
        migrations.AddField(
            model_name="adresse",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adresses",
                to="cities_light.country",
                verbose_name="Pays (Cities Light)",
            ),
        ),
        migrations.AddField(
            model_name="adresse",
            name="region_cl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adresses",
                to="cities_light.region",
                verbose_name="Région (Cities Light)",
            ),
        ),
    ]
